### ISSUE TITLE
Example Client has an error?

### ISSUE THREAD

**Issue by gkapellmann** [chkr1011/CoAPnet#5]
Hello, 

In the example, it says to create a connection the builder is setup as:

var connectOptions = new CoapClientConnectOptionsBuilder()
            .WithHost("GW-B8D7AF2B3EA3.fritz.box")
            .WithPort(5684)
            .WithDtlsTransportLayer(new DtlsCoapTransportLayerOptionsBuilder()
                .WithPreSharedKey("IDENTITY", "lqxbBH6o2eAKSo5A")
                .Build())
            .Build();

However, when the package is downloaded from the nuget link, yhis line doesnt seem to be accepted:

.WithDtlsTransportLayer(new DtlsCoapTransportLayerOptionsBuilder()

And Visual studio only seems to find:

.WithTransportLayer

How will the example be setup in this case?

Thank you!

**Comment by chkr1011** [comment]
Hi, sorry for the long delay. I updated the sample because this API was changed in the meantime.

**Comment by gkapellmann** [comment]
No worries!
Ok, thank you! 

Awesome libs btw :)
